### User sign up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name": "Eddie Olivas",
    "company": "Chrysalis Web Development fave",
    "address": "16023 Mitchell Ave. Tustin, CA 92780",
    "phone": 71470907363,
    "email": "eddie@chrysaliswebdevelopment.com",
    "password": "password1234"
}

### User sign in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    "email": "eddie@chrysaliswebdevelopment.com",
    "password": "newPassword12345"
} 

### Get user profile endpoint
GET http://localhost:3001/v1/user/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVkZGllQGNocnlzYWxpc3dlYmRldmVsb3BtZW50LmNvbSIsImlhdCI6MTYzMzIwNDU1MiwiZXhwIjoxNjMzMjA1NDUyfQ.ScOuZeSGqxMwLfDIZXPTEdu7efC9s7YhzhyqttXNZpw

### Token routers

### Get fresh JWT
GET http://localhost:3001/v1/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVkZGllQGdtYWlsLmNvbSIsImlhdCI6MTYzMzAzMjA3OCwiZXhwIjoxNjM1NjI0MDc4fQ.48LrlnyGUgmh2WaZ3MXKP6IwC0QrOfdSPh49BQwFv3w

### Password reset request endpoint
POST http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email": "eddie@chrysaliswebdevelopment.com"
}

### Update new password
PATCH http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email": "eddie@chrysaliswebdevelopment.com",
    "pin": "942111",
    "password": "newPassword12345"
}

### User logout endpoint
DELETE http://localhost:3001/v1/user/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVkZGllQGNocnlzYWxpc3dlYmRldmVsb3BtZW50LmNvbSIsImlhdCI6MTYzMzI5NTM0MCwiZXhwIjoxNjMzMjk2MjQwfQ.dgNAVm3UrmliML6I7ZFdPgWeT8zT0hi41bnUioFDKyQ

### Create ticket endpoint
POST http://localhost:3001/v1/ticket
Content-Type: application/json

{
    "subject": "Help me fix the thing",
    "sender": "Bob",
    "message": "I don't know how to do things, please help."
}