### User sign up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name": "Eddie Olivas",
    "company": "Chrysalis Web Development fave",
    "address": "16023 Mitchell Ave. Tustin, CA 92780",
    "phone": 71470907363,
    "email": "eddie@gmail.com",
    "password": "password1234"
}

### User sign in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    "email": "eddie@gmail.com",
    "password": "password1234"
} 
