### User sign up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name": "Eddie Olivas",
    "company": "Chrysalis Web Development fave",
    "address": "16023 Mitchell Ave. Tustin, CA 92780",
    "phone": 71470907363,
    "email": "eddie@chrysaliswebdevelopment.com",
    "password": "password1234"
}

### User sign in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    "email": "eddie@chrysaliswebdevelopment.com",
    "password": "newPassword12345"
} 

### Get user profile endpoint
GET http://localhost:3001/v1/user/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVkZGllQGNocnlzYWxpc3dlYmRldmVsb3BtZW50LmNvbSIsImlhdCI6MTYzMzIwNDU1MiwiZXhwIjoxNjMzMjA1NDUyfQ.ScOuZeSGqxMwLfDIZXPTEdu7efC9s7YhzhyqttXNZpw

### Token routers

### Get fresh JWT
GET http://localhost:3001/v1/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVkZGllQGdtYWlsLmNvbSIsImlhdCI6MTYzMzAzMjA3OCwiZXhwIjoxNjM1NjI0MDc4fQ.48LrlnyGUgmh2WaZ3MXKP6IwC0QrOfdSPh49BQwFv3w

### Password reset request endpoint
POST http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email": "eddie@chrysaliswebdevelopment.com"
}

### Update new password
PATCH http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email": "eddie@chrysaliswebdevelopment.com",
    "pin": "942111",
    "password": "newPassword12345"
}

### User logout endpoint
DELETE http://localhost:3001/v1/user/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVkZGllQGNocnlzYWxpc3dlYmRldmVsb3BtZW50LmNvbSIsImlhdCI6MTYzMzI5NTM0MCwiZXhwIjoxNjMzMjk2MjQwfQ.dgNAVm3UrmliML6I7ZFdPgWeT8zT0hi41bnUioFDKyQ

### Create ticket endpoint
POST http://localhost:3001/v1/ticket
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVkZGllQGNocnlzYWxpc3dlYmRldmVsb3BtZW50LmNvbSIsImlhdCI6MTYzMzg5MjIzNCwiZXhwIjoxNjMzODkzMTM0fQ.6AmnxO6SpwQhAH4GmaxAmzItczPNd1iOCgd3c-fVNds
Content-Type: application/json

{
    "subject": "My computer broke",
    "sender": "Bob Joe",
    "message": "My computer totally broke, please help."
}

### Get tickets endpoint
GET http://localhost:3001/v1/ticket
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVkZGllQGNocnlzYWxpc3dlYmRldmVsb3BtZW50LmNvbSIsImlhdCI6MTYzMzg4NzEyNiwiZXhwIjoxNjMzODg4MDI2fQ.OaLH7yqwBLGg9VpB5oXGifZT2r2S6_XxJTcmwyKUxwM

### Get ticket by ID endpoint
GET http://localhost:3001/v1/ticket/616326184634cb883d4d7527
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVkZGllQGNocnlzYWxpc3dlYmRldmVsb3BtZW50LmNvbSIsImlhdCI6MTYzMzg4NzEyNiwiZXhwIjoxNjMzODg4MDI2fQ.OaLH7yqwBLGg9VpB5oXGifZT2r2S6_XxJTcmwyKUxwM

### Update ticket by ID endpoint
PUT http://localhost:3001/v1/ticket/61632f27cb7c8473f7d8c4b5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVkZGllQGNocnlzYWxpc3dlYmRldmVsb3BtZW50LmNvbSIsImlhdCI6MTYzMzg5MTM3NiwiZXhwIjoxNjMzODkyMjc2fQ.vCuyoPI8tNlhS2S10QbS2KFem4ERa4bnaEW85Ow4UcU
Content-Type: application/json

{
    "sender": "Bob",
    "message": "I will fix your computer asdfsds."
}

### Close ticket by ID
PATCH http://localhost:3001/v1/ticket/close-ticket/61632f27cb7c8473f7d8c4b5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVkZGllQGNocnlzYWxpc3dlYmRldmVsb3BtZW50LmNvbSIsImlhdCI6MTYzMzg5MTM3NiwiZXhwIjoxNjMzODkyMjc2fQ.vCuyoPI8tNlhS2S10QbS2KFem4ERa4bnaEW85Ow4UcU
Content-Type: application/json

### Delete ticket by ID
DELETE http://localhost:3001/v1/ticket/616337968d8b7133db0fd4a7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVkZGllQGNocnlzYWxpc3dlYmRldmVsb3BtZW50LmNvbSIsImlhdCI6MTYzMzg5MjIzNCwiZXhwIjoxNjMzODkzMTM0fQ.6AmnxO6SpwQhAH4GmaxAmzItczPNd1iOCgd3c-fVNds
Content-Type: application/json